language: r
cache: packages
latex: false
sudo: required

before_install:
  - sudo cp fonts/ -r /usr/local/share/fonts
  - sudo fc-cache -f -v
#  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
#  - sudo add-apt-repository ppa:opencpu/jq --yes
#  - sudo apt-get --yes --force-yes update -qq
#  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libv8-dev
#  - sudo apt-get install --yes libjq-dev libprotobuf-dev libprotoc-dev protobuf-compiler

install:
  - R -e "install.packages('bookdown')"
  - R -e "install.packages('tinytex')"
  - R -e "install.packages('tibble')"
  - R -e "install.packages('kableExtra')"
  - R -e "install.packages('readxl')"
  - R -e "install.packages('bench')"
  - R -e "install.packages('testthat')"
  - R -e "install.packages('ggplot2')"
  - R -e "install.packages('reticulate')"
  - R -e "tinytex::install_tinytex(repository = 'http://ftp.cvut.cz/tex-archive/')"
  #- R -e "tinytex::reinstall_tinytex()"

script:
  - make both
  
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash _deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change
